# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# configuration editor integration
config_editor:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# debugging
logger:
  default: info
  logs:
    homeassistant.core: debug
    custom_components.pyscript: debug

frontend:
  extra_module_url:
    - /hacsfiles/custom-sidebar/custom-sidebar.js

# DuckDNS
#duckdns:
#  domain: !secret duckdns_domain
#  access_token: !secret duckdns_access_token

# custom date and time formats
sensor:
  # Minimal configuration of the standard time and date sensor
  - platform: time_date
    display_options:
      - "date_time_iso"

template:
# Build on the standard sensor to produce one that can be customized
  - sensor:
      - unique_id: "customdatetimewidget_time"
        name: "Time"
        state: "{{ as_timestamp(states('sensor.date_time_iso')) | timestamp_custom('%I:%M\u00a0%p') }}"
        icon: "mdi:clock"
  - sensor:
    - unique_id: "customdatetimewidget_date"
      name: "Date"
      state: "{{ as_timestamp(states('sensor.date_time_iso')) | timestamp_custom('%A %B\u00a0%d') }}"
      icon: "mdi:calendar"

# bedroom heater
  - sensor:
      - unique_id: "eb3bde281fa6d2ecacx3gn_voltage"
        name: "bedroom_heater_smart_plug_voltage"
        state: "{{ states.switch.bedroom_heater_smart_plug_2.attributes.voltage }}"
        unit_of_measurement: "V"
        icon: "mdi:lightning-bolt-outline"
  - sensor:
      - unique_id: "eb3bde281fa6d2ecacx3gn_current"
        name: "bedroom_heater_smart_plug_current"
        state: "{{ states.switch.bedroom_heater_smart_plug_2.attributes.current }}"
        unit_of_measurement: "mA"
        icon: "mdi:current-ac"
  - sensor:
      - unique_id: "eb3bde281fa6d2ecacx3gn_current_consumption"
        name: "bedroom_heater_smart_plug_current_consumption"
        state: "{{ states.switch.bedroom_heater_smart_plug_2.attributes.current_consumption }}"
        unit_of_measurement: "W"
        icon: "mdi:lightbulb-on"
        
# fernery lights
  - sensor:
      - unique_id: "eb2559339bee59e01cqnzr_voltage"
        name: "fernery_lights_smart_plug_voltage"
        state: "{{ states.switch.bedroom_heater_smart_plug_2.attributes.voltage }}"
        unit_of_measurement: "V"
        icon: "mdi:lightning-bolt-outline"
  - sensor:
      - unique_id: "eb2559339bee59e01cqnzr_current"
        name: "fernery_lights_smart_plug_current"
        state: "{{ states.switch.bedroom_heater_smart_plug_2.attributes.current }}"
        unit_of_measurement: "mA"
        icon: "mdi:current-ac"
  - sensor:
      - unique_id: "eb2559339bee59e01cqnzr_current_consumption"
        name: "fernery_lights_smart_plug_current_consumption"
        state: "{{ states.switch.bedroom_heater_smart_plug_2.attributes.current_consumption }}"
        unit_of_measurement: "W"
        icon: "mdi:lightbulb-on"
        
# christmas lights
  - sensor:
      - unique_id: "ebf671e742048f2f501p6h_voltage"
        name: "christmas_lights_smart_plug_voltage"
        state: "{{ states.switch.bedroom_heater_smart_plug_2.attributes.voltage }}"
        unit_of_measurement: "V"
        icon: "mdi:lightning-bolt-outline"
  - sensor:
      - unique_id: "ebf671e742048f2f501p6h_current"
        name: "christmas_lights_smart_plug_current"
        state: "{{ states.switch.bedroom_heater_smart_plug_2.attributes.current }}"
        unit_of_measurement: "mA"
        icon: "mdi:current-ac"
  - sensor:
      - unique_id: "ebf671e742048f2f501p6h_current_consumption"
        name: "christmas_lights_smart_plug_current_consumption"
        state: "{{ states.switch.bedroom_heater_smart_plug_2.attributes.current_consumption }}"
        unit_of_measurement: "W"
        icon: "mdi:lightbulb-on"

# study heater
  - sensor:
      - unique_id: "ebfcd0f6cac4a3419brjqk_voltage"
        name: "study_heater_smart_plug_voltage"
        state: "{{ states.switch.bedroom_heater_smart_plug_2.attributes.voltage }}"
        unit_of_measurement: "V"
        icon: "mdi:lightning-bolt-outline"
  - sensor:
      - unique_id: "ebfcd0f6cac4a3419brjqk_current"
        name: "study_heater_smart_plug_current"
        state: "{{ states.switch.bedroom_heater_smart_plug_2.attributes.current }}"
        unit_of_measurement: "mA"
        icon: "mdi:current-ac"
  - sensor:
      - unique_id: "ebfcd0f6cac4a3419brjqk_current_consumption"
        name: "study_heater_smart_plug_current_consumption"
        state: "{{ states.switch.bedroom_heater_smart_plug_2.attributes.current_consumption }}"
        unit_of_measurement: "W"
        icon: "mdi:lightbulb-on"

# nursery heater
  - sensor:
      - unique_id: "ebc032d9a161327439tawl_voltage"
        name: "nursery_heater_smart_plug_voltage"
        state: "{{ states.switch.bedroom_heater_smart_plug_2.attributes.voltage }}"
        unit_of_measurement: "V"
        icon: "mdi:lightning-bolt-outline"
  - sensor:
      - unique_id: "ebc032d9a161327439tawl_current"
        name: "nursery_heater_smart_plug_current"
        state: "{{ states.switch.bedroom_heater_smart_plug_2.attributes.current }}"
        unit_of_measurement: "mA"
        icon: "mdi:current-ac"
  - sensor:
      - unique_id: "ebc032d9a161327439tawl_current_consumption"
        name: "nursery_heater_smart_plug_current_consumption"
        state: "{{ states.switch.bedroom_heater_smart_plug_2.attributes.current_consumption }}"
        unit_of_measurement: "W"
        icon: "mdi:lightbulb-on"



