switch:
  # pushbutton switch
  - platform: gpio
    pin: 23
    restore_mode: ALWAYS_OFF
    id: gate_pushbutton_relay
    name: "Gate Remote"
    icon: "mdi:gate"
    on_turn_on:
    - delay: 200ms
    - switch.turn_off: gate_pushbutton_relay
  
  # power supply switch
  - platform: gpio
    pin: 22
    restore_mode: RESTORE_DEFAULT_ON 
    id: gate_power_relay
    name: "Gate Power Supply"
    icon: "mdi:power-plug-outline"

sensor:
  # measure WiFi signal strength
  - platform: wifi_signal
    id: gate_wifi_signal
    name: "Gate WiFi Signal"
    #update_interval: 60s
    accuracy_decimals: 1
    filters:
      - throttle_average: 300s

  # measure supply voltage
  - platform: adc
    pin: 33
    attenuation: auto
    name: "Gate Supply Voltage"
    id: gate_supply_v
    unit_of_measurement: "V"
    accuracy_decimals: 2
    icon: "mdi:lightning-bolt-outline"
    filters:
      - multiply: 8.551 # based on R1 = 1.5 MOhm and R2 = 200 kOhm resistors on the voltage divider
      - throttle_average: 300s
    # on_value_range:
    #   - below: 20.0
    #     then:
    #       - switch.turn_on: gate_pushbutton_relay
    #       - delay: 30s
    #       - switch.turn_off: gate_power_relay
    #   - above: 22.0
    #     then:
    #       - switch.turn_on: gate_power_relay
    